### ISSUE TITLE
Support not-global persistent variables

### ISSUE THREAD

**Issue by fbarresi** [fbarresi/TwinCatAdsTool#17]
As mentioned in #14  the Software is designed for looking only for **global** persistent variables. Any other persistent parameter not global reachable is ignored. 

# Goal
Support all persistent variables

# Problems
- Search may last longer
- Restore action cannot be applied in batches (because an FB or a Pgr cannot be serialized as json)

# Approaches
- Add a custom section into the backup json (like `{"$_non-global":{...}`)
- maybe with a deep search disabled by default, but with manual switch

**Comment by fbarresi** [comment]
Hey @temmat ! I hope you're well. I made the changes we discussed in #14 . 
A pre-release is available [here](https://github.com/fbarresi/TwinCatAdsTool/releases/tag/1.2.10).
I finally removed the possibility to use the "flat-symbol-list" since through that it's impossible to find deeply nested persistent fields.
I think it would be fine if you would be my beta-tester and give this pre-release a try and share your impressions or open more issues.

**Comment by temmat** [comment]
Hello,
thanks for the heads-up. Sure, I'll have access to a real system in the upcoming week and will do some testing.

**Comment by temmat** [comment]
Hello again @fbarresi ,
so a couple of things I noticed from the get go.

The transition from .NET 4.6.2 to .NET 5.0 seems to have brought some issues with the versions of the packages used, but anyway, the build succeeds albeit with some warnings.

Reading seems to work for the test setup that I checked today, even for the nested persistent variables with multi-instance function blocks. Writing back of these values seems to be ok too.

There is however now something wrong with writing an object as in the case:

`case JObject value:`
`await clientService.Client.WriteJson(variable.Name + "." + p.Name, value,force: true);`

This ends with an "Ads-Error 0x710: Symbol could not be found" practically always when there is a nested UDT within a UDT (for example). I think this was not a problem in the previous versions - at least in the 1.1.48 which I still have opened just for reference.

Manually resolving the hierarchy down to the last structure level (as suggested in the #14 ) this backup becomes functional too.
I hope the attached files demonstrate what I mean - there's also a picture of the actual dummy/test hierarchical structure of the GVL.

![GVL_Structure](https://user-images.githubusercontent.com/33503719/116890343-cdbaa880-ac2d-11eb-8808-d808060c7324.PNG)
[Backup_2021-05-03-153305_1.2.1_manually_resolved_working.json.txt](https://github.com/fbarresi/TwinCatAdsTool/files/6415459/Backup_2021-05-03-153305_1.2.1_manually_resolved_working.json.txt)
[Backup_2021-05-03-153305_1.2.1_problematic.json.txt](https://github.com/fbarresi/TwinCatAdsTool/files/6415460/Backup_2021-05-03-153305_1.2.1_problematic.json.txt)


While doing these tests another problem arised, but this is a separate issue with #22 as far as I can tell it doesn't have anything to do with the latest changes, I just didn't test it earlier...happens with the 1.1.48 version too.

**Comment by fbarresi** [comment]
Hi @temmat !
Thank you for sharing a feedback. 

It should now be fixed in version [1.2.11](https://github.com/fbarresi/TwinCatAdsTool/releases/1.2.11).

**Comment by temmat** [comment]
Hello,
I just did some testing on the same setup as previously and the same issue/error occurs even with 1.2.11.

Actually the change from 1.2.10 to 1.2.11 made things worse, since now even the variables that were restored correctly in 1.2.10 (the ones under "MAIN." in the example I'm working with) can't be restored anymore.

The individual variables in 1.20.10 are restored correctly, the objects (as in nested structures) are not. Now since these variables that were treated individually in 1.20.10 are included into the parent object in 1.20.11 they can't be restored back anymore.

The way I mad it work in the previous post was the other way around...that is to separate the variables from the object/structure to individual declarations. The "Backup_2021-05-03-153305_1.2.1_manually_resolved_working.json.txt" contains the variables individually so that they can be restored correctly - this is a customised file I prepared to show how the organization of the objects/variables can be used to make it work.

The "Backup_2021-05-03-153305_1.2.1_problematic.json.txt" contains an object (that can't be restored correctly) and other individual variables "MAIN." that can be restored correctly. This is the way 1.20.10 saves the variables.

Now I include a further file that contains the saved file as of the version 1.20.11, where none of the variables can be restored properly.
[Backup_2021-05-28-124024_1.20.11.json.txt](https://github.com/fbarresi/TwinCatAdsTool/files/6560383/Backup_2021-05-28-124024_1.20.11.json.txt)

Hope this helps.
Best regards

**Comment by fbarresi** [comment]
Hi! Thank you for your double check. 
I've hopefully found this bug while writing variables.

**Comment by temmat** [comment]
Version 1.20.12 changes the issue a little bit, but it's still not OK.
The structures that are defined as Persistent at the top level work.

The hierarchically structured instances of function blocks, that contain mixed persistent and non persistent children are read out correctly ... this is ok; but then they are now aggregated into the hierarchical structure (this was changed with version 1.20.11, 1.20.10 is better regarding this issue) and once they are written, they are written as objects which fails, since we don't have content for the entire object but for some parts of it, hence we get a "Null object cannot be converted to a value type" again. I think it would be better if you keep the current code for writing, but revert to the version 1.20.10 of treating - and storing separately - the individual variables.  

I have additionally just encountered another real case situation where the current way of dealing with persistent variables fails...this time already at the reading stage and it comes again to dealing with structures as objects. It is very reproducible and happens if you have a Non persistent user defined data type (structure) which includes one of it items a persistent user defined data type. Twincat allows persistence definition either when defining the variable itself or already when defining the data type.
In case of the later there's an exception thrown at this line:

![TwinCatAdsTool-1 2 12-Exception](https://user-images.githubusercontent.com/33503719/120341468-2f3a6980-c2f7-11eb-838b-2b8bd7961abc.PNG)

If you have a test Twincat  3 installation I can provide the test project that includes all the discussed variable constructs.

**Comment by fbarresi** [comment]
Hi! 
Thank you for helping me with your comments and tries!
I think it would be great if your could share here a dummy twincat project for testing such variables. Of course a don't need any logic, only variables declarations.
I think I know what you mean, I will try to fix it at glance in the software.
Best regards,
FB

**Comment by temmat** [comment]
Here you go, this is the same project I use currently for testing the TwincatADSTool.
It contains more or less all the variable constructs and function block instance types I encountered in real-world cases; of course in a simplified and logic-less manner. Some variables have a simple counter behind them so you have some changing values that can be used to test the "compare" function in the ADSTool too.
It's a dummy project, so there's no other actual use behind it.

Please rename the file to .tnzip and open as archive from within Twincat (renamed due to GitHub file type limitation).
It's pinned to 3.1.4024.12 version, but there's nothing special in it so you can probably use any 3.1.4024 versionor possibly even older.


[TwinCATDummy.zip](https://github.com/fbarresi/TwinCatAdsTool/files/6582930/TwinCATDummy.zip)

**Comment by fbarresi** [comment]
Hi @temmat!

Thank you for sharing the project. I added some time variables and put the project directly in the repo. I think I can be helpful and useful to keep use cases and tricky constructs ready for testing.

I already found and fixed a couple of bugs. I was able to read and restore all variables and complex types in the project. I will go further with more tests in these days.

Best regards,
FB

**Comment by temmat** [comment]
There already were some TIME variables in the dummy project that I sent, at least if t was exported properly; specifically persistent TIME variables "GVL.PersVarGlobalTime1" and  "MAIN.TestFB1_DB1.BP_tSetup". 
But sure, add any variables that you find necessary for testing purposes.

Best regards

**Comment by temmat** [comment]
The current development branch (1.12.14 release) seems to be working for the issues discussed above.
I've only had time to do some quick tests, but so far it looks OK. I'll have an update in a couple of days.

Best regards

**Comment by fbarresi** [comment]
Hi @temmat, 
Thank you for your advises. I also had chance to test the latest release in a couple of real situation and I think it was good!
I'm going to close this issue and merge as soon as I wrote the whole release notes.
I've already started to collect new features for version 1.3, if you have some enhancement scenario, I would be glad to have your opinion or contribution.

Best regards,
FB

**Comment by temmat** [comment]
Agreed on closing the issue.

Sure, depending on the time at hand I might be able to contribute some code to the project too, but at the current state I can't contribute to the "develop" branch from my fork, and the "develop" branch is the one that contains all the changes we discussed about, including the Twincat test project (If you find it appropriate I could contribute some additional functionality to this test project).

Best regards
